#!/bin/bash

#虚拟机镜像文件目录
IMG_DIR=/var/lib/libvirt/images

#镜像模板名称
BASEVM=rh7

while :
do
    read -p "请输入你想要的虚拟机名称：" NEWVM
    if [ -z $NEWVM ];then
        echo -e "\033[31m虚拟机名称不能为空！！！\033[0m"
        continue
    fi
    if [ -e $IMG_DIR/${NEWVM}.img ]; then
        echo -e "\033[31mFile exists.\033[0m"
        continue
    fi
    break
done

echo -en "Creating Virtual Machine disk image......\t"

#创建前端盘（COW）
qemu-img create -f qcow2 -b $IMG_DIR/${BASEVM}.img $IMG_DIR/${NEWVM}.img &> /dev/null
if [ $? -eq 0 ];then
    echo -e "\e[32;1m[OK]\e[0m"
else
    echo "some trouble happened,perhaps template is not exist"
    exit
fi

#基于模板创建新的xml配置文件
cat /var/lib/libvirt/images/rh7.xml > /tmp/myvm.xml
##################################################################
#xml配置文件中必须修改的地方有：
#虚拟机名称
#uuid
#镜像文件名称
#mac地址
sed -i "/<name>${BASEVM}/s/${BASEVM}/${NEWVM}/" /tmp/myvm.xml

sed -i "/uuid/s/<uuid>.*<\/uuid>/<uuid>$(uuidgen)<\/uuid>/" /tmp/myvm.xml

sed -i "/${BASEVM}\.img/s/${BASEVM}/${NEWVM}/" /tmp/myvm.xml

#随机生成mac地址
#替换旧mac地址
nmac=$(echo 00:60:2f:`openssl rand -hex 3 | sed 's/\(..\)/\1:/g; s/.$//'`)
sed -i "86s/74:52:08:05:01:01/$nmac/" /tmp/myvm.xml

nmac=$(echo 00:60:3f:`openssl rand -hex 3 | sed 's/\(..\)/\1:/g; s/.$//'`)
sed -i "94s/74:52:08:05:01:02/$nmac/" /tmp/myvm.xml

nmac=$(echo 00:60:4f:`openssl rand -hex 3 | sed 's/\(..\)/\1:/g; s/.$//'`)
sed -i "102s/74:52:08:05:01:03/$nmac/" /tmp/myvm.xml

nmac=$(echo 00:60:5f:`openssl rand -hex 3 | sed 's/\(..\)/\1:/g; s/.$//'`)
sed -i "110s/74:52:08:05:01:04/$nmac/" /tmp/myvm.xml

echo -en "Defining new virtual machine......\t\t"

#根据xml文件定义新的虚拟机
virsh define /tmp/myvm.xml &> /dev/null
if [ $? -ne 0 ];then
    echo -e "\033[31m配置文件有误,请手动检查...\033[0m"
    rm -rf /var/lib/libvirt/images/${NEWVM}.img
    rm -rf /etc/libvirt/qemu/${NEWVM}.xml
    exit
else
    echo -e "\e[32;1m[OK]\e[0m"
fi
######################虚拟机创建完成##########################
echo "修改虚拟机配置中..."
sleep 2

#创建挂载点并确认是否已经存在---》离线挂载
mountpoint="/mnt/virtimage"

if [ ! -d $mountpoint ];then
    mkdir $mountpoint
    echo -e "\033[43;32m请稍等...\033[0m"
fi
#查询guestmount工具包是否安装
rpm -q libguestfs-tools-c &> /dev/null
if [ $? -ne 0 ];then
    yum -y install libguestfs-tools-c 
fi
if [ $? -ne 0 ];then
    echo -e "\033[31m请检查yum源配置或手动安装\033[0m"
    exit
fi
#########################################################################################
#定义函数判断IP合法性
CheckIPaddr()                                                             
{
    echo $1| grep "^[0-9]\{1,3\}\.\([0-9]\{1,3\}\.\)\{2\}[0-9]\{1,3\}$"
    if [ $? -ne 0 ];then
        return 1
    fi
    ipaddr=$1
    #以点号分隔，取出ip中四列的值
    num1=`echo $ipaddr | awk -F "." '{print $1}'`
    num2=`echo $ipaddr | awk -F "." '{print $2}'`
    num3=`echo $ipaddr | awk -F "." '{print $3}'`
    num4=`echo $ipaddr | awk -F "." '{print $4}'`
    for num in $num1 $num2 $num3 $num4
    do
        if [ $num -gt 255 ] || [ $num -lt 0 ];then
            return 1
        fi
    done
    return 0
}
###########################################################################################
guestmount -d $NEWVM -i $mountpoint
if [ $? -ne 0 ];then
    echo -e "\033[31m发生了点意外，请再试一次...\033[0m"
    umount $mountpoint
    exit
fi
#read -p "请输入需要修改的网卡名称：" eth0
while true
do
    read -p "请输入IP地址(点分十进制)：" addr
    CheckIPaddr $addr
    if [ $? -ne 0 ];then
        echo -e "\033[31m请输入正确的IP地址！\033[0m"
        continue
    fi
    break
done
while :
do
    read -p "请输入子网掩码(默认24):" mask
    mask=${mask:-24}
    if [ $mask -gt 32 ] || [ $mask -lt 0 ];then
        echo -e "\033[31m请输入合法的子网掩码！！！\033[0m"
        continue
    else echo $mask | grep -E "^[0-9]{1,2}$" &> /dev/null
        if [ $? -ne 0 ];then
            echo -e "\033[31m请输入正确的子网掩码！！！\033[0m"
            continue
        fi
    fi
    break
done

################################################################################################
#设置IP
echo "
TYPE=Ethernet
BOOTPROTO=none
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
NAME=eth0
DEVICE=eth0
ONBOOT=yes
IPADDR=$addr
PREFIX=$mask" > $mountpoint/etc/sysconfig/network-scripts/ifcfg-eth0
################################################################################################
#设置主机名
read -p "请输入主机名(默认template)：" htname
htname=${htname:-tempalte}
echo "$htname" > $mountpoint/etc/hostname
################################################################################################
#设置网络yum源
while :
do
    read -p "请输入网络Yum源的IP地址(默认：192.168.4.254)：" yum
    yum=${yum:-192.168.4.254}
    CheckIPaddr $yum
    if [ $? -ne 0 ];then
        echo "请输入正确的IP地址！！！"
        continue
    fi
    break
done

echo "[rhel]
name=rhel
baseurl=http://$yum/rhel7
enabled=1
gpgcheck=0" > $mountpoint/etc/yum.repos.d/rhel7.repo
################################################################################################
while :
do
    read -p "是否选择更改selinux的状态为disabled（y/n）：" fchoice
    fchoice=${fchoice:-y}
    if [ "$fchoice" == "y" ];then
        sed -i '/SELINUX/s/=enforcing/=disabled/' $mountpoint/etc/selinux/config
        if [ $? -ne 0 ];then
            echo -e "\033[31m发生了一点错误，请稍后手动修改selinux默认状态...\033[0m"
        else
            echo -e "\033[35mselinux已设置成关闭状态\033[0m"
        fi
    elif [ "$fchoice" == "n" ];then
        echo -e "\033[43;35m爱咋滴咋滴,自己去设置！！！\033[0m"
    else
        echo -e "\033[31m请重新输入！！！\033[0m"
        continue
    fi
    break
done
################################################################################################
while :
do
    read -p "是否选择更改firewalld区域为trusted（y/n）：" sechoice
    sechoice=${sechoice:-y}
    if [ "$sechoice" == "y" ];then
        sed -i '/DefaultZone/s/=public/=trusted/' $mountpoint/etc/firewalld/firewalld.conf
        if [ $? -ne 0 ];then
            echo -e "\033[43;35m发生了一点错误，请稍后手动修改selinux默认状态...\033[0m"
        else
            echo -e "\033[35mfirewalld默认区域已设置成trusted\033[0m"
        fi
    elif [ "$sechoice" == "n" ];then
        echo -e "\033[43;35m爱咋滴咋滴，自己去设置！！！\033[0m"
    else
        echo -e "\033[31m请重新输入！！！\033[0m"
        continue
    fi
    break
done
################################################################################################
echo "set nu
set autoindent
set ai
autocmd FileType yml setlocal ai et ts=2 " > $mountpoint/root/.vimrc
################################################################################################
echo  -e "\033[33m设置完成...\033[0m"
umount $mountpoint
echo  -e "\033[36m请稍等...\033[0m"
sleep 5

while :
do
    read -p "是否现在启动虚拟机（y/n）："  choice
    choice=${choice:-y}
    if [ "$choice" == "y" ];then
        echo -e "\033[33m正在启动虚拟机...\033[0m"
        virsh start $NEWVM
        exit
    elif [ "$choice" == "n" ];then
        echo -e "\033[35m请手动启动虚拟机...\033[0m"
        exit
    else
        echo "\033[31m请输入正确的选项!!!\033[0m"
        continue
    fi
    break
done
